export default interface IPlan {
  type?: String | null;
  planName?: String | null;
  subType?: String | null;
  specialty?: String | null;
  faculty?: String | null;
  studyType?: String | null;
  studyForm?: String | null;
  group?: String | null;
  count?: Number | null;
  codeTIN?: String | null;
  nameEducationalComponent?: String | null;
  exams?: String | null;
  credits?: String | null;
  courseWork?: Number | null;
  graduateWork?: Number | null;
  countCredits?: Number | null;
  totalValue?: Number | null;
  total?: Number | null;
  lectures?: Number | null;
  practical?: Number | null;
  laboratory?: Number | null;
  independentWork?: Number | null;
  ff1?: Number | String | null;
  ff1__1?: Number | String | null;
  ff2?: Number | String | null;
  ff2__1?: Number | String | null;
  ss1?: Number | String | null;
  ss1__1?: Number | String | null;
  ss2?: Number | String | null;
  ss2__1?: Number | String | null;
  tt1?: Number | String | null;
  tt1__1?: Number | String | null;
  tt2?: Number | String | null;
  tt2__1?: Number | String | null;
  th1?: Number | String | null;
  th1__1?: Number | String | null;
  th2?: Number | String | null;
  th2__1?: Number | String | null;
  year?: String | null;
  week?: String | null;
}
